# -*- coding: utf-8 -*-
"""difficulty_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MF_D9muEV8SJSamcFxLIZRSHdUaWh5JO
"""

import pandas as pd

# Base difficulty mapping
BASE_DIFFICULTY = {
    "Linear Regression": "Beginner",
    "Gradient Descent": "Beginner",
    "Activation Functions": "Beginner",
    "Backpropagation": "Intermediate",
    "Neural Networks": "Intermediate",
    "Overfitting & Regularization": "Advanced"
}

DIFFICULTY_LEVELS = ["Beginner", "Intermediate", "Advanced"]

def adjust_difficulty(base, intent):
    idx = DIFFICULTY_LEVELS.index(base)

    if intent == "Doubt" and idx < 2:
        idx += 1
    elif intent in ["Example", "Revision"] and idx > 0:
        idx -= 1

    return DIFFICULTY_LEVELS[idx]

def predict_difficulty(topic, intent):
    base = BASE_DIFFICULTY.get(topic, "Beginner")
    return adjust_difficulty(base, intent)

# Example test
if __name__ == "__main__":
    sample_inputs = [
        ("Backpropagation", "Explanation"),
        ("Backpropagation", "Example"),
        ("Overfitting & Regularization", "Doubt"),
        ("Linear Regression", "Revision")
    ]

    for topic, intent in sample_inputs:
        difficulty = predict_difficulty(topic, intent)
        print(f"Topic: {topic}, Intent: {intent} → Difficulty: {difficulty}")