# -*- coding: utf-8 -*-
"""topic_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Jy7IKwIbIzPjik1s7COp0eASb6G9ub8
"""

import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

# Load dataset
df = pd.read_csv("/content/student_queries.csv")

# Load embedding model
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

# Generate embeddings
X = embedding_model.encode(df["query_text"].tolist())

# Target variable
y = df["topic"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

# Train classifier
topic_clf = LogisticRegression(
    max_iter=1000,
    multi_class="multinomial"
)
topic_clf.fit(X_train, y_train)

# Predictions
y_pred = topic_clf.predict(X_test)

# Evaluation
accuracy = accuracy_score(y_test, y_pred)
print("Topic Classification Accuracy:", round(accuracy, 3))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))