# -*- coding: utf-8 -*-
"""embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYjWgACQjt_eUy7LeGzm2d95Kv7nQcZH
"""

import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.model_selection import train_test_split
import numpy as np

# Load dataset
df = pd.read_csv("../student_queries.csv")

# Load pre-trained sentence embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")

# Convert queries to embeddings
embeddings = model.encode(df["query_text"].tolist())

# Convert embeddings to numpy array
X = np.array(embeddings)

# Labels for later use
y_intent = df["intent"]
y_topic = df["topic"]
y_difficulty = df["difficulty_level"]

# Train-test split (70-30)
X_train, X_test, y_intent_train, y_intent_test = train_test_split(
    X, y_intent, test_size=0.3, random_state=42
)

print("Embeddings generated successfully!")
print("Embedding shape:", X.shape)
print("Train samples:", X_train.shape[0])
print("Test samples:", X_test.shape[0])