# -*- coding: utf-8 -*-
"""learning_logs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mmRa954gnrsTbVt0HpSdViYol3uf9cxo
"""

import pandas as pd
import random
import os

random.seed(42)

students = range(1, 26)
topics = [
    "Linear Regression",
    "Gradient Descent",
    "Backpropagation",
    "Neural Networks",
    "Overfitting & Regularization"
]

rows = []

for student_id in students:
    previous_topic = None

    for topic in topics:
        attempts = random.randint(1, 4)
        time_spent = random.randint(15, 45)

        base_score = random.randint(40, 60)
        quiz_score = min(100, base_score + attempts * random.randint(5, 10))

        # Confidence score calculation
        confidence = (
            (quiz_score / 100)
            - (attempts * 0.05)
            + (time_spent / 60) * 0.1
        )
        confidence = round(max(0, min(confidence, 1)), 2)

        rows.append({
            "student_id": student_id,
            "topic": topic,
            "quiz_score": quiz_score,
            "attempts": attempts,
            "time_spent_min": time_spent,
            "confidence_score": confidence,
            "previous_topic": previous_topic
        })

        previous_topic = topic

df = pd.DataFrame(rows)

# Create the output directory if it doesn't exist
output_directory = "../data_output"
os.makedirs(output_directory, exist_ok=True)

df.to_csv(os.path.join(output_directory, "student_learning_logs.csv"), index=False)

print("Student learning interaction dataset generated successfully!")
print("Total records:", len(df))