# -*- coding: utf-8 -*-
"""recommendation_policy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15kgqf3ndhpuQ3N9RvA01f4273iFuzcCv
"""

TOPIC_SEQUENCE = [
    "Linear Regression",
    "Gradient Descent",
    "Backpropagation",
    "Neural Networks",
    "Overfitting & Regularization"
]

def get_next_topic(current_topic):
    if current_topic not in TOPIC_SEQUENCE:
        return TOPIC_SEQUENCE[0]

    idx = TOPIC_SEQUENCE.index(current_topic)
    if idx < len(TOPIC_SEQUENCE) - 1:
        return TOPIC_SEQUENCE[idx + 1]
    return current_topic


def recommend_learning_path(student_state):
    avg_score = student_state["avg_quiz_score"]
    avg_attempts = student_state["avg_attempts"]
    confidence = student_state["confidence_score"]
    current_topic = student_state["current_topic"]

    # Default values
    action = "Continue"
    difficulty_adjustment = "Same"
    next_topic = current_topic

    # Revision logic
    if avg_score < 50 or confidence < 0.45:
        action = "Revision"
        difficulty_adjustment = "Decrease"
        next_topic = current_topic

    # Progression logic
    elif avg_score > 75 and confidence > 0.7:
        action = "Advance"
        difficulty_adjustment = "Increase"
        next_topic = get_next_topic(current_topic)

    # Struggle handling
    elif avg_attempts > 3:
        action = "Revision"
        difficulty_adjustment = "Same"
        next_topic = current_topic

    return {
        "next_topic": next_topic,
        "action": action,
        "difficulty_adjustment": difficulty_adjustment
    }


# Example test
if __name__ == "__main__":
    sample_state = {
        "avg_quiz_score": 48,
        "avg_attempts": 3.2,
        "confidence_score": 0.42,
        "current_topic": "Backpropagation"
    }

    recommendation = recommend_learning_path(sample_state)
    print(recommendation)