# -*- coding: utf-8 -*-
"""student_state.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GGWjr_nxv8mROw9ER4fL3Lt_QQ6VS8yi
"""

import pandas as pd

class StudentState:
    def __init__(self, student_id, learning_log_df):
        self.student_id = student_id
        self.learning_log_df = learning_log_df

        self.state = self._compute_state()

    def _compute_state(self):
        student_data = self.learning_log_df[
            self.learning_log_df["student_id"] == self.student_id
        ]

        avg_quiz_score = student_data["quiz_score"].mean()
        avg_attempts = student_data["attempts"].mean()
        avg_time_spent = student_data["time_spent_min"].mean()
        confidence_score = student_data["confidence_score"].mean()

        current_topic = student_data.iloc[-1]["topic"]
        last_topic = student_data.iloc[-1]["previous_topic"]

        return {
            "student_id": self.student_id,
            "current_topic": current_topic,
            "last_topic": last_topic,
            "avg_quiz_score": round(avg_quiz_score, 2),
            "avg_attempts": round(avg_attempts, 2),
            "avg_time_spent": round(avg_time_spent, 2),
            "confidence_score": round(confidence_score, 2)
        }

    def get_state(self):
        return self.state


# Example usage
if __name__ == "__main__":
    df = pd.read_csv("student_learning_logs.csv")

    student_state = StudentState(student_id=1, learning_log_df=df)
    print(student_state.get_state())