# -*- coding: utf-8 -*-
"""generate_queries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SBTnsmJX7OZKrUW3yqzjI0YUhlD8HOiB
"""

import pandas as pd
import random
import os

# Fixed seed for reproducibility
random.seed(42)

topics = {
    "Linear Regression": "Beginner",
    "Gradient Descent": "Beginner",
    "Backpropagation": "Intermediate",
    "Neural Networks": "Intermediate",
    "Overfitting & Regularization": "Advanced",
    "Activation Functions": "Beginner"
}

intent_templates = {
    "Explanation": [
        "I don’t understand how {} works",
        "Can you explain {} in simple terms?",
        "I am confused about {}"
    ],
    "Example": [
        "Can you give an example of {}?",
        "Show me a practical example of {}",
        "I need a real-world example for {}"
    ],
    "Doubt": [
        "Why does {} sometimes fail?",
        "What happens if {} is not tuned properly?",
        "Why is {} important in models?"
    ],
    "Revision": [
        "Can you quickly revise {}?",
        "Give me a short recap of {}",
        "I want to revise {} once again"
    ]
}

rows = []

for topic, base_difficulty in topics.items():
    for intent, templates in intent_templates.items():
        for _ in range(10):  # controls dataset size
            template = random.choice(templates)
            query = template.format(topic)

            # Difficulty logic
            if intent == "Doubt" and base_difficulty == "Advanced":
                difficulty = "Advanced"
            elif intent == "Explanation":
                difficulty = base_difficulty
            else:
                difficulty = "Beginner"

            rows.append({
                "query_text": query,
                "intent": intent,
                "topic": topic,
                "difficulty_level": difficulty
            })

df = pd.DataFrame(rows)

# Ensure the output directory exists
output_path = "../data_output/student_queries.csv"
directory = os.path.dirname(output_path)
if not os.path.exists(directory):
    os.makedirs(directory, exist_ok=True)

df.to_csv(output_path, index=False)

print("Student query dataset generated successfully!")
print("Total queries:", len(df))