# -*- coding: utf-8 -*-
"""__init__.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pIbCMtpJ2RruTy0V0Tk2ksxbyHst-mzL
"""

import os

os.makedirs("models", exist_ok=True)
os.makedirs("learning_path", exist_ok=True)

open("models/__init__.py", "w").close()
open("learning_path/__init__.py", "w").close()